### PR TITLE
update for Read API

### PR DESCRIPTION
**Pull request by PatrickFarley**
## Purpose

* The BatchRead API is meant to replace RecognizeText, which is now deprecated. I've updated the code sample to do the same function, but with BatchRead instead of RecognizeText.

## Does this introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by PatrickFarley** [comment]
@ChrisHMSFT , please have someone review this PR

**Comment by v-jerkin** [comment]
Looks good to me.

**Comment by PatrickFarley** [comment]
@v-jerkin are you able to merge the PR?

**Comment by v-jerkin** [comment]
No, but I know someone who can.

@wiazur can you merge this?

**Comment by wiazur** [comment]
@v-jerkin Merged.

**Pull request merged**
